new Schema("spectrum:midnight_solution_converting")
    .simpleKey("ingredient", "inputItem")
    .simpleKey("result", "outputItem")

new Schema("spectrum:fusion_shrine")
    .simpleKey("time", "intNumber")
    .simpleKey("experience", "doubleNumber")
    .simpleKey("fluid", "inputFluid")
    .simpleKey("ingredients", "inputItemArray")
    .simpleKey("result", "outputItem")
    .simpleKey("copy_nbt", "bool", false || true)
    .simpleKey("required_advancement", "anyString", "")
    .simpleKey("world_conditions", "anyString", "")
    .simpleKey("start_crafting_effect", "anyString", "")
    .simpleKey("during_crafting_effects", "anyString", "")
    .simpleKey("finish_crafting_effect", "anyString", "")

new Schema("spectrum:pedestal")
    .simpleKey("time", "intNumber")
    .simpleKey("tier", "nonEmptyString", "basic" || "simple" || "advanced" || "complex") 
    .simpleKey("cyan", "intNumber", 0)
    .simpleKey("magenta", "intNumber", 0)
    .simpleKey("yellow", "intNumber", 0)
    .simpleKey("black", "intNumber", 0)
    .simpleKey("white", "intNumber", 0)
    .simpleKey("experience", "doubleNumber", 0.0)