	[ars_nouveau.amethyst_golem]
		#紫水晶傀儡的收集时间
		# Default: 80
		# Range: > 0
		deposit_using_time = 5
		#紫水晶傀儡的扫描冷却
		# Default: 3600
		# Range: > 0
		scan_cooldown = 5
		#紫水晶傀儡的收获冷却
		# Default: 1200
		# Range: > 0
		harvest_cooldown = 50
		#紫水晶傀儡的收获持续时间
		# Default: 130
		# Range: > 0
		harvest_using_time = 50
		#紫水晶傀儡的收获间隔
		# Default: 40
		# Range: > 1
		harvest_interval = 5
		#紫水晶傀儡的拾取冷却
		# Default: 60
		# Range: > 0
		pickup_cooldown = 50
		#紫水晶傀儡的拾取时间
		# Default: 80
		# Range: > 0
		pickup_using_time = 5
		#紫水晶傀儡的转化冷却
		# Default: 6000
		# Range: > 0
		convert_cooldown = 5000
		#紫水晶傀儡的转化时间
		# Default: 120
		# Range: > 0
		convert_using_time = 100
		#紫水晶傀儡的催生冷却
		# Default: 300
		# Range: > 0
		grow_cooldown = 20
		#紫水晶傀儡的催生时间
		# Default: 120
		# Range: > 0
		grow_using_time = 0
		#紫水晶傀儡每次催生的最大母岩数量
		# Default: 4
		# Range: > 1
		grow_max_blocks = 5

	[ars_nouveau.ars_nouveau_other]
		#法术感测器的激活时长
		# Default: 40
		# Range: > 1
		spell_sensor_output_duration = 2
		#附魔装置的工作时长
		# Default: 210
		# Range: > 1
		enchanting_apparatus_crafting_length = 100
		#飞行物品的归一化时间
		# Default: 80.0
		# Range: 0.0 ~ 1.7976931348623157E308
		flying_item_normalize_time = 10.0
		#注魔台取源时粒子生成概率分母
		# Default: 3
		# Range: > 1
		imbuement_rand_bound_draining = 18
		#注魔台空闲时粒子生成概率分母
		# Default: 6
		# Range: > 1
		imbuement_rand_bound_idle = 36

	[ars_nouveau.volcanic_sourcelink]
		#火之精华产生的魔源
		# Default: 2000
		# Range: > 0
		fire_essence_source = 2500
		#石头转换成岩浆块消耗的进度
		# Default: 150
		# Range: > 0
		stone_to_magma_block_consume = 8
		#岩浆块熔岩消耗的进度
		# Default: 200
		# Range: > 0
		magma_block_to_lava_consume = 12

	[ars_nouveau.starbuncle]
		#星宝石兽拾取物品的冷却
		# Default: 5
		# Range: > 0
		starbuncle_take_item_cooldown = 5
		#星宝石兽寻找物品的冷却
		# Default: 30
		# Range: > 0
		starbuncle_find_item_cooldown = 10

	[ars_nouveau.source_jar]
		#魔源罐存储的魔源上限
		# Default: 10000
		# Range: > 0
		source_jar_max_source = 100000

	[ars_nouveau.relay]
		#魔源中转器存储和运输的魔源上限
		# Default: 1000
		# Range: > 0
		relay_max_source = 10000
		#魔源中转器：分流型存储和运输的魔源上限
		# Default: 2500
		# Range: > 0
		relay_splitter_max_source = 25000

[create]
	#在切割配方没有写配方时间时，动力锯使用的配方时间，机械动力默认值为50
	# Default: 75
	# Range: > 0
	default_saw_recipe_time = 75
	#在搅拌配方没有写配方时间时，动力搅拌器使用的配方时间，机械动力默认值为100
	# Default: 85
	# Range: > 0
	default_mixer_recipe_time = 85
	#注液器的处理时间，机械动力默认值为20
	# Default: 19
	# Range: > 6
	spout_process_time = 19

[create_enchantment_industry]
	#打印机的处理时间
	# Default: 19
	# Range: > 6
	printer_process_time = 19
	#在打磨配方没有写配方时间时，动力砂轮使用的配方时间，附魔工业默认值为50
	# Default: 30
	# Range: > 0
	grindstone_recipe_time = 30

[ratatouille]
	#冷冻块的处理时间
	# Default: 20
	# Range: > 1
	frozen_block_process_time = 20

[spectrum]
	#微生物转换的时间
	# Default: 40
	# Range: > 1
	decay_conversion_delay = 10
	#午夜溶液伤害间隔
	# Default: 20
	# Range: > 1
	midnight_solution_hurt_interval = 20
	#午夜溶液伤害倍率
	# Default: 1.0
	# Range: 0.0 ~ 3.4028234663852886E38
	midnight_solution_damage_mult = 4.0

	[spectrum.idols]
		#魔盒冷却时间
		# Default: 40
		# Range: > 0
		idol_cooldown = 10
		#充气魔盒一次充气的史莱姆数量上限
		# Default: 1
		# Range: > 1
		slime_idol_convert_num = 8

[minecraft]
	#雪傀儡投掷雪球的偏移系数
	# Default: 12.0
	# Range: 0.0 ~ 3.4028234663852886E38
	snow_golem_inaccuracy = 0.0

[starbunclemania]
	#流体魔源通道的最大魔源存储量
	# Default: 5000
	# Range: > 1
	fluid_sourcelink_max_source = 20000
	#流体魔源通道的传输速率
	# Default: 2000
	# Range: > 1
	fluid_sourcelink_transfer_rate = 10000
