ServerEvents.tags("block", event => {

    let create_wrench = [
        '#betterend:pedestal',
        '#forge:sites/villager_job',
        '#minecraft:buttons',
        '#minecraft:pressure_plates',
        '#minecraft:rails',
        "#c:chests",
        '#quark:crystal_lamp',
        '#functionalstorage:drawer',

        'alexscaves:azure_magnet',
        'alexscaves:hologram_projector',
        'alexscaves:magnetic_activator',
        'alexscaves:magnetic_light',
        'alexscaves:quarry',
        'alexscaves:scarlet_magnet',

        'anvilcraft:active_silencer',
        'anvilcraft:auto_crafter',
        'anvilcraft:batch_crafter',
        'anvilcraft:block_devourer',
        'anvilcraft:block_placer',
        'anvilcraft:charge_collector',
        'anvilcraft:charger',
        'anvilcraft:chute',
        'anvilcraft:crab_trap',
        'anvilcraft:corrupted_beacon',
        'anvilcraft:discharger',
        'anvilcraft:ember_anvil',
        'anvilcraft:ferrite_core_magnet_block',
        'anvilcraft:giant_anvil',
        'anvilcraft:heater',
        'anvilcraft:heliostats',
        'anvilcraft:hollow_magnet_block',
        'anvilcraft:impact_pile',
        'anvilcraft:induction_light',
        'anvilcraft:item_collector',
        'anvilcraft:load_monitor',
        'anvilcraft:magnet_block',
        'anvilcraft:magnetic_chute',
        'anvilcraft:menger_sponge',
        'anvilcraft:overseer',
        'anvilcraft:thermoelectric_converter',
        'anvilcraft:transmission_pole',
        'anvilcraft:transparent_crafting_table',
        'anvilcraft:piezoelectric_crystal',
        'anvilcraft:power_converter_big',
        'anvilcraft:power_converter_middle',
        'anvilcraft:power_converter_small',
        'anvilcraft:remote_transmission_pole',
        'anvilcraft:royal_anvil',
        'anvilcraft:ruby_laser',
        'anvilcraft:ruby_prism',
        'anvilcraft:space_overcompressor',
        'anvilcraft:spectral_anvil',
        'anvilcraft:stamping_platform',
        'anvilcraft:simple_chute',

        'functionalstorage:oak_1',
        'functionalstorage:spruce_1',
        'functionalstorage:birch_1',
        'functionalstorage:jungle_1',
        'functionalstorage:acacia_1',
        'functionalstorage:dark_oak_1',
        'functionalstorage:crimson_1',
        'functionalstorage:warped_1',
        'functionalstorage:mangrove_1',
        'functionalstorage:cherry_1',
        'functionalstorage:framed_1',
        'functionalstorage:fluid_1',

        'functionalstorage:oak_2',
        'functionalstorage:spruce_2',
        'functionalstorage:birch_2',
        'functionalstorage:jungle_2',
        'functionalstorage:acacia_2',
        'functionalstorage:dark_oak_2',
        'functionalstorage:crimson_2',
        'functionalstorage:warped_2',
        'functionalstorage:mangrove_2',
        'functionalstorage:cherry_2',
        'functionalstorage:framed_2',
        'functionalstorage:fluid_2',

        'functionalstorage:oak_4',
        'functionalstorage:spruce_4',
        'functionalstorage:birch_4',
        'functionalstorage:jungle_4',
        'functionalstorage:acacia_4',
        'functionalstorage:dark_oak_4',
        'functionalstorage:crimson_4',
        'functionalstorage:warped_4',
        'functionalstorage:mangrove_4',
        'functionalstorage:cherry_4',
        'functionalstorage:framed_4',
        'functionalstorage:fluid_4',

        'functionalstorage:compacting_drawer',
        'functionalstorage:compacting_framed_drawer',
        'functionalstorage:storage_controller',
        'functionalstorage:framed_storage_controller',
        'functionalstorage:controller_extension',
        'functionalstorage:framed_controller_extension',
        'functionalstorage:simple_compacting_drawer',
        'functionalstorage:framed_simple_compacting_drawer',
        'functionalstorage:armory_cabinet',
        'functionalstorage:ender_drawer',

        'minecraft:bell',
        'minecraft:calibrated_sculk_sensor',
        'minecraft:chiseled_bookshelf',
        'minecraft:honey_block',
        'minecraft:sculk_sensor',
        'minecraft:slime_block',
        'minecraft:tnt',

        'quark:chute',
        'quark:crafter',
        'quark:ender_watcher',
        'quark:gravisand',
        'quark:iron_rod',
        'quark:magnet',
        'quark:redstone_randomizer',
        
        'spelunkery:carved_nephrite',
        'spelunkery:compression_blast_miner',
        'spelunkery:nephrite_diode',
        'spelunkery:nephrite_fountain',
        'spelunkery:nephrite_siphon',

        'supplementaries:bellows',
        'supplementaries:cannon',
        'supplementaries:cog_block',
        'supplementaries:crank',
        'supplementaries:crystal_display',
        'supplementaries:faucet',
        'supplementaries:lock_block',
        'supplementaries:redstone_illuminator',
        'supplementaries:relayer',
        'supplementaries:speaker_block',
        'supplementaries:spring_launcher',
        'supplementaries:turn_table',
        'supplementaries:wind_vane'
    ]
    event.add('create:wrench_pickup', create_wrench)
    
})